### ISSUE TITLE
Python 2.6 issue: datetime.timedelta has no attribute 'total_seconds'

### ISSUE THREAD

**Issue by bialecki** [nkrode/RedisLive#5]
Works fine in 2.7, just an issue for 2.6.
